### ISSUE TITLE
has_tag Function Returning Incorrect Boolean Value

### ISSUE THREAD

**Issue by brichard1638** [jsugarelli/tagr#1]
I'm not sure it will be easy to reproduce the bug for this issue but I have several data objects in my environment. When I apply the has_tag function on an object that has not been tagged using the tagr package, the function returns a TRUE value. The correct value is FALSE.

I will provide information related to the version of RStudio being used as well as the version of R that was used when the error occurred.
R Information
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

RStudio Information
$mode
[1] "desktop"

$version
[1] ‘2023.6.1.524’

$long_version
[1] "2023.06.1+524"

$release_name
[1] "Mountain Hydrangea"

**Comment by jsugarelli** [comment]
Thanks. A new version (1.0.1) has been submitted to CRAN that fixes the problem.
